name: Deploy Docs to Synology

on:
  push:
    branches: [main]
    paths: ['docs/**']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    # IMPORTANTE: Hemos eliminado la línea 'container:', ahora corre en el host del runner
    steps:
      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
        env:
          GIT_CONFIG_PARAMETERS: "'url.https://git.natxocc.com/.insteadOf=http://gitea:3000/'"

      - name: Sincronizar archivos
        run: |
          # 1. Verificamos si la carpeta existe en el NAS
          if [ -d "/volume1/web/sigpro" ]; then
            echo "Carpeta destino encontrada."
          else
            echo "ERROR: No veo /volume1/web/sigpro. Revisa los montajes de Docker del Runner."
            exit 1
          fi

          # 2. Sincronizamos (el runner ya suele tener rsync o cp)
          rsync -av --delete docs/ /volume1/web/sigpro/
          
          # 3. Ajustamos permisos para Web Station
          chmod -R 755 /volume1/web/sigpro/