name: Test DNS

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: |
          ping -c 1 gitea || echo "No ping"
          getent hosts gitea
          curl -v http://gitea:3000 2>&1 | head -10