name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: node:20-bullseye
      options: >-
        --dns 192.168.1.1
        --add-host gitea:192.168.1.100
        --add-host git.natxocc.com:192.168.1.100
    steps:
      - name: Configurar Entorno
        run: |
          # Esto obliga a Git a redirigir CUALQUIER URL que use el puerto 3000 al puerto 3333
          # Por si Gitea le envía la URL interna al runner
          git config --global url."http://192.168.1.100:3333/".insteadOf "http://gitea:3000/"
          git config --global --add safe.directory /workspace/natxocc/sigpro
          git config --global http.sslVerify false

      - name: Checkout código
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Publicar en NPM
        run: |
          npm install
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}