name: Publish to NPM

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: oven/bun:latest
      # ESTO SOLUCIONA EL ERROR DE RED:
      options: --network host
    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Instalar dependencias
        run: bun install

      - name: Publicar en NPM
        run: |
          echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > .npmrc
          # Usamos el publish de bun o npm, ambos funcionan si las dependencias están listas
          npm publish --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}